### ISSUE TITLE
Cannot find Chrome Binary

### ISSUE THREAD

**Issue by NateDreier** [jitsi/jitsi-meet-torture#210]
Hello,

**EDIT:** can get error message if needed.

I am getting an issue titled "Cannot find Chrome Binary" Goes into looking at "(Driver info: chromedriver=70.0.3538.16 ...."

I am executing this on a Ubuntu minimal version, should I be doing this on say, Ubuntu Desktop with Chrome installed? Has anyone else come across a similar issue?

Any help would be great.

Thanks!
Nate

**Comment by damencho** [comment]
Aa, do you have chrome installed there? And a running some kind of x server where chrome can launch?

**Comment by NateDreier** [comment]
Issue resolved. Called for help sooner than needed. 
Ran through everything on a Jitsi quick install on Ubuntu Desktop 16.04
- Maven
- Chrome
- Java 8
- Jitsi-meet quick install

Everything worked great. Thanks guys for keeping this up and supported.

**Comment by Manni79** [comment]
> Issue resolved. Called for help sooner than needed. Ran through everything on a Jitsi quick install on Ubuntu Desktop 16.04
> 
> * Maven
> * Chrome
> * Java 8
> * Jitsi-meet quick install
> 
> Everything worked great. Thanks guys for keeping this up and supported.

Hello @NateDreier, what exactly was your solution? As I understand the post of @damencho, then chrome should be installed automatically because it is listed in POM, right? But  you installed Chrome and Java 8 manually, right?

I get the same error, also on a ubuntu installation. Currently I run it in a windows WSL2 installation. For now I havn't installed chrome manually, because I thought maven will install it. Do I understand it correctly or a manual install is needed?

I run a test with:
`mvn test -Djitsi-meet.instance.url="https://meet.example.com"`


Complete Error:
```
[53] ---=== Testing LockRoomTest ===---
[53] No participant type specified for prefix: web.participant1, will use Chrome...
java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary
Host info: host: 'xxxx', ip: '127.0.1.1'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.22'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, allow-insecure-localhost, use-fake-ui-for-media-stream, use-fake-device-for-media-s..., disable-plugins, mute-audio, disable-infobars, autoplay-policy=no-user-ges..., auto-select-desktop-capture..., no-sandbox, disable-dev-shm-usage, disable-setuid-sandbox, disable-gpu, use-file-for-fake-audio-cap...], extensions: [], prefs: {intl.accept_languages: en-US}}, goog:loggingPrefs: org.openqa.selenium.logging...}]}]
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.jitsi.meet.test.web.WebParticipantFactory.startWebDriver(WebParticipantFactory.java:372)
        at org.jitsi.meet.test.web.WebParticipantFactory.doCreateParticipant(WebParticipantFactory.java:122)
        at org.jitsi.meet.test.web.WebParticipantFactory.doCreateParticipant(WebParticipantFactory.java:38)
        at org.jitsi.meet.test.base.ParticipantFactory.createParticipant(ParticipantFactory.java:35)
        at org.jitsi.meet.test.base.ParticipantHelper.createParticipant(ParticipantHelper.java:163)
        at org.jitsi.meet.test.web.WebTestBase.joinParticipant(WebTestBase.java:303)
        at org.jitsi.meet.test.web.WebTestBase.joinParticipantAndWait(WebTestBase.java:422)
        at org.jitsi.meet.test.web.WebTestBase.ensureOneParticipant(WebTestBase.java:82)
        at org.jitsi.meet.test.web.WebTestBase.ensureOneParticipant(WebTestBase.java:56)
        at org.jitsi.meet.test.LockRoomTest.setupClass(LockRoomTest.java:50)
        at org.jitsi.meet.test.base.AbstractBaseTest.setupClassPrivate(AbstractBaseTest.java:195)
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
        at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary
Host info: host: 'xxxx', ip: '127.0.1.1'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.22'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, allow-insecure-localhost, use-fake-ui-for-media-stream, use-fake-device-for-media-s..., disable-plugins, mute-audio, disable-infobars, autoplay-policy=no-user-ges..., auto-select-desktop-capture..., no-sandbox, disable-dev-shm-usage, disable-setuid-sandbox, disable-gpu, use-file-for-fake-audio-cap...], extensions: [], prefs: {intl.accept_languages: en-US}}, goog:loggingPrefs: org.openqa.selenium.logging...}]}]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
        at org.jitsi.meet.test.web.WebParticipantFactory.lambda$startWebDriver$0(WebParticipantFactory.java:364)
        ... 4 more
[53] Just create ChromeDriver, may hang!
[53] TestFailure:
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: cannot find Chrome binary
Host info: host: 'xxx', ip: '127.0.1.1'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.133.1-microsoft-standard-WSL2', java.version: '11.0.22'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, allow-insecure-localhost, use-fake-ui-for-media-stream, use-fake-device-for-media-s..., disable-plugins, mute-audio, disable-infobars, autoplay-policy=no-user-ges..., auto-select-desktop-capture..., no-sandbox, disable-dev-shm-usage, disable-setuid-sandbox, disable-gpu, use-file-for-fake-audio-cap...], extensions: [], prefs: {intl.accept_languages: en-US}}, goog:loggingPrefs: org.openqa.selenium.logging...}]}]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
        at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:108)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:83)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:72)
        at org.jitsi.meet.test.web.WebParticipantFactory.startWebDriver(WebParticipantFactory.java:395)
        at org.jitsi.meet.test.web.WebParticipantFactory.doCreateParticipant(WebParticipantFactory.java:122)
        at org.jitsi.meet.test.web.WebParticipantFactory.doCreateParticipant(WebParticipantFactory.java:38)
        at org.jitsi.meet.test.base.ParticipantFactory.createParticipant(ParticipantFactory.java:35)
        at org.jitsi.meet.test.base.ParticipantHelper.createParticipant(ParticipantHelper.java:163)
        at org.jitsi.meet.test.web.WebTestBase.joinParticipant(WebTestBase.java:303)
        at org.jitsi.meet.test.web.WebTestBase.joinParticipantAndWait(WebTestBase.java:422)
        at org.jitsi.meet.test.web.WebTestBase.ensureOneParticipant(WebTestBase.java:82)
        at org.jitsi.meet.test.web.WebTestBase.ensureOneParticipant(WebTestBase.java:56)
        at org.jitsi.meet.test.LockRoomTest.setupClass(LockRoomTest.java:50)
        at org.jitsi.meet.test.base.AbstractBaseTest.setupClassPrivate(AbstractBaseTest.java:195)
        at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
        at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Thanks a lot!**

**Comment by damencho** [comment]
You need to install chrome. And java 11. This post is 6 years old.

Please, when you have questions or problems use the community forum, thank you.
