### ISSUE TITLE
LipSyncTest fails with various errors

### ISSUE THREAD

**Issue by TheNetStriker** [jitsi/jitsi-meet-torture#269]
I've managed to get all tests for my own Jitsi installation to succeed except the LipSyncTest. At first I got this error when running the test:

```
[1] TestFailure:
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.jitsi.meet.test.LipSyncTest.testLipSync(LipSyncTest.java:190)
....
```
Now for some reason I get the following error:
```
[1] TestFailure:
java.lang.AssertionError: A problem with the conf occurred
	at org.testng.Assert.fail(Assert.java:96)
	at org.jitsi.meet.test.tasks.HeartbeatTask.await(HeartbeatTask.java:204)
	at org.jitsi.meet.test.LipSyncTest.testLipSync(LipSyncTest.java:182)
....
```
I also did see that the Chrome browser does seem to have some problems with my webcam. When running the test I get the following error in the browser: "Your camera does not satisfy some of the required constraints."

I also opened the same url manually in Chrome 81, but there the webcam worked without any problems. Any idea what could cause this problem?

**Comment by damencho** [comment]
Lipsync test is something we have not ran for years because of chrome limitation we had turned off lipsync. Now that is gone, and probably we will again look into turning it back on at some point.
