### ISSUE TITLE
got an error while run the mvn test command

### ISSUE THREAD

**Issue by rfakit** [jitsi/jitsi-meet-torture#274]
hi there,
i came accross to this error and i hace no idea what to do. i'll be really delighted if you can help me.

this is the error:

[ERROR] Tests run: 275, Failures: 25, Errors: 0, Skipped: 247, Time elapsed: 38.753 s <<< FAILURE! - in TestSuite
[ERROR] setupClassPrivate(org.jitsi.meet.test.ActiveSpeakerTest)  Time elapsed: 2.246 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.ActiveSpeakerTest.setupClass(ActiveSpeakerTest.java:45)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.ActiveSpeakerTest.setupClass(ActiveSpeakerTest.java:45)

[ERROR] setupClassPrivate(org.jitsi.meet.test.AudioOnlyTest)  Time elapsed: 3.654 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.AudioOnlyTest.setupClass(AudioOnlyTest.java:43)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.AudioOnlyTest.setupClass(AudioOnlyTest.java:43)

[ERROR] setupClassPrivate(org.jitsi.meet.test.AvatarTest)  Time elapsed: 5.008 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.AvatarTest.setupClass(AvatarTest.java:50)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.AvatarTest.setupClass(AvatarTest.java:50)

[ERROR] setupClassPrivate(org.jitsi.meet.test.ChatPanelTest)  Time elapsed: 6.37 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.ChatPanelTest.setupClass(ChatPanelTest.java:43)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.ChatPanelTest.setupClass(ChatPanelTest.java:43)

[ERROR] setupClassPrivate(org.jitsi.meet.test.DataChannelTest)  Time elapsed: 7.695 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.DataChannelTest.setupClass(DataChannelTest.java:42)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.DataChannelTest.setupClass(DataChannelTest.java:42)

[ERROR] setupClassPrivate(org.jitsi.meet.test.DisplayNameTest)  Time elapsed: 9.027 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.DisplayNameTest.setupClass(DisplayNameTest.java:47)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.DisplayNameTest.setupClass(DisplayNameTest.java:47)

[ERROR] setupClassPrivate(org.jitsi.meet.test.EndConferenceTest)  Time elapsed: 10.37 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.EndConferenceTest.setupClass(EndConferenceTest.java:36)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.EndConferenceTest.setupClass(EndConferenceTest.java:36)

[ERROR] setupClassPrivate(org.jitsi.meet.test.EtherpadTest)  Time elapsed: 11.718 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.EtherpadTest.setupClass(EtherpadTest.java:49)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.EtherpadTest.setupClass(EtherpadTest.java:49)

[ERROR] setupClassPrivate(org.jitsi.meet.test.FilmstripOnlyTest)  Time elapsed: 1.314 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.FilmstripOnlyTest.setupClass(FilmstripOnlyTest.java:42)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.FilmstripOnlyTest.setupClass(FilmstripOnlyTest.java:42)

[ERROR] setupClassPrivate(org.jitsi.meet.test.FollowMeTest)  Time elapsed: 2.664 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.FollowMeTest.setupClass(FollowMeTest.java:46)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.FollowMeTest.setupClass(FollowMeTest.java:46)

[ERROR] setupClassPrivate(org.jitsi.meet.test.InviteTest)  Time elapsed: 3.962 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.InviteTest.setupClass(InviteTest.java:46)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.InviteTest.setupClass(InviteTest.java:46)

[ERROR] testIFrameAPI(org.jitsi.meet.test.IFrameAPITest)  Time elapsed: 1.899 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.IFrameAPITest.testIFrameAPI(IFrameAPITest.java:82)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.IFrameAPITest.testIFrameAPI(IFrameAPITest.java:82)

[ERROR] testLipSync(org.jitsi.meet.test.LipSyncTest)  Time elapsed: 1.418 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.LipSyncTest.testLipSync(LipSyncTest.java:114)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.LipSyncTest.testLipSync(LipSyncTest.java:114)

[ERROR] setupClassPrivate(org.jitsi.meet.test.LockRoomTest)  Time elapsed: 2.733 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.LockRoomTest.setupClass(LockRoomTest.java:50)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.LockRoomTest.setupClass(LockRoomTest.java:50)

[ERROR] setupClassPrivate(org.jitsi.meet.test.MuteTest)  Time elapsed: 4.05 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.MuteTest.setupClass(MuteTest.java:56)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.MuteTest.setupClass(MuteTest.java:56)

[ERROR] testFilmstripHiddenInOneOnOne(org.jitsi.meet.test.OneOnOneTest)  Time elapsed: 1.33 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.OneOnOneTest.testFilmstripHiddenInOneOnOne(OneOnOneTest.java:58)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.OneOnOneTest.testFilmstripHiddenInOneOnOne(OneOnOneTest.java:58)

[ERROR] testSwitchToP2P(org.jitsi.meet.test.Peer2PeerTest)  Time elapsed: 1.328 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.Peer2PeerTest.testSwitchToP2P(Peer2PeerTest.java:49)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.Peer2PeerTest.testSwitchToP2P(Peer2PeerTest.java:49)

[ERROR] setupClassPrivate(org.jitsi.meet.test.SharedVideoTest)  Time elapsed: 2.654 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.SharedVideoTest.setupClass(SharedVideoTest.java:72)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.SharedVideoTest.setupClass(SharedVideoTest.java:72)

[ERROR] setupClassPrivate(org.jitsi.meet.test.SinglePortTest)  Time elapsed: 3.962 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.SinglePortTest.setupClass(SinglePortTest.java:38)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.SinglePortTest.setupClass(SinglePortTest.java:38)

[ERROR] setupClassPrivate(org.jitsi.meet.test.StartMutedTest)  Time elapsed: 5.317 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.StartMutedTest.setupClass(StartMutedTest.java:39)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.StartMutedTest.setupClass(StartMutedTest.java:39)

[ERROR] setupClassPrivate(org.jitsi.meet.test.StopVideoTest)  Time elapsed: 7.049 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.StopVideoTest.setupClass(StopVideoTest.java:57)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.StopVideoTest.setupClass(StopVideoTest.java:57)

[ERROR] setupClassPrivate(org.jitsi.meet.test.SwitchVideoTest)  Time elapsed: 8.849 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.SwitchVideoTest.setupClass(SwitchVideoTest.java:57)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.SwitchVideoTest.setupClass(SwitchVideoTest.java:57)

[ERROR] setupClassPrivate(org.jitsi.meet.test.TileViewTest)  Time elapsed: 10.188 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.TileViewTest.setupClass(TileViewTest.java:51)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.TileViewTest.setupClass(TileViewTest.java:51)

[ERROR] setupClassPrivate(org.jitsi.meet.test.UDPTest)  Time elapsed: 11.496 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.UDPTest.setupClass(UDPTest.java:37)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.UDPTest.setupClass(UDPTest.java:37)

[ERROR] setupClassPrivate(org.jitsi.meet.test.VideoLayoutTest)  Time elapsed: 12.808 s  <<< FAILURE!
io.github.bonigarcia.wdm.WebDriverManagerException: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.VideoLayoutTest.setupClass(VideoLayoutTest.java:44)
Caused by: io.github.bonigarcia.wdm.WebDriverManagerException: A response error is detected: HTTP/1.1 403 Forbidden
	at org.jitsi.meet.test.VideoLayoutTest.setupClass(VideoLayoutTest.java:44)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ActiveSpeakerTest>AbstractBaseTest.setupClassPrivate:187->setupClass:45->WebTestBase.ensureThreeParticipants:206->WebTestBase.ensureThreeParticipants:185->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   AudioOnlyTest>AbstractBaseTest.setupClassPrivate:187->setupClass:43->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   AvatarTest>AbstractBaseTest.setupClassPrivate:187->setupClass:50->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   ChatPanelTest>AbstractBaseTest.setupClassPrivate:187->setupClass:43->WebTestBase.ensureOneParticipant:57->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   DataChannelTest>AbstractBaseTest.setupClassPrivate:187->setupClass:42->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   DisplayNameTest>AbstractBaseTest.setupClassPrivate:187->setupClass:47->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   EndConferenceTest>AbstractBaseTest.setupClassPrivate:187->setupClass:36->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   EtherpadTest>AbstractBaseTest.setupClassPrivate:187->setupClass:49->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   FilmstripOnlyTest>AbstractBaseTest.setupClassPrivate:187->setupClass:42->WebTestBase.ensureTwoParticipants:107->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   FollowMeTest>AbstractBaseTest.setupClassPrivate:187->setupClass:46->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   IFrameAPITest.testIFrameAPI:82->WebTestBase.ensureOneParticipant:69->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   InviteTest>AbstractBaseTest.setupClassPrivate:187->setupClass:46->WebTestBase.ensureOneParticipant:57->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   LipSyncTest.testLipSync:114->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   LockRoomTest>AbstractBaseTest.setupClassPrivate:187->setupClass:50->WebTestBase.ensureOneParticipant:57->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   MuteTest>AbstractBaseTest.setupClassPrivate:187->setupClass:56->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   OneOnOneTest.testFilmstripHiddenInOneOnOne:58->WebTestBase.ensureTwoParticipants:107->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   Peer2PeerTest.testSwitchToP2P:49->WebTestBase.ensureTwoParticipants:107->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   SharedVideoTest>AbstractBaseTest.setupClassPrivate:187->setupClass:72->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   SinglePortTest>AbstractBaseTest.setupClassPrivate:187->setupClass:38->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   StartMutedTest>AbstractBaseTest.setupClassPrivate:187->setupClass:39->WebTestBase.ensureOneParticipant:57->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   StopVideoTest>AbstractBaseTest.setupClassPrivate:187->setupClass:57->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   SwitchVideoTest>AbstractBaseTest.setupClassPrivate:187->setupClass:57->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   TileViewTest>AbstractBaseTest.setupClassPrivate:187->setupClass:51->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   UDPTest>AbstractBaseTest.setupClassPrivate:187->setupClass:37->WebTestBase.ensureTwoParticipants:94->WebTestBase.ensureTwoParticipants:129->WebTestBase.ensureTwoParticipantsInternal:154->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[ERROR]   VideoLayoutTest>AbstractBaseTest.setupClassPrivate:187->setupClass:44->WebTestBase.ensureOneParticipant:57->WebTestBase.ensureOneParticipant:83->WebTestBase.joinParticipantAndWait:391->WebTestBase.joinParticipant:301 » WebDriverManager
[INFO] 
[ERROR] Tests run: 275, Failures: 25, Errors: 0, Skipped: 247
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  41.036 s
[INFO] Finished at: 2020-05-02T14:30:20+04:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project jitsi-meet-torture: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/arya/rsync/Git-Projects/jitsi-meet-torture/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by damencho** [comment]
https://github.com/bonigarcia/webdrivermanager#http-response-code-403
