### ISSUE TITLE
problem on MaxUsersTest

### ISSUE THREAD

**Issue by jjmasdeu** [jitsi/jitsi-meet-torture#302]
I run ;   
mvn test -Djitsi-meet.instance.url="https://meet.activo.nl" -Djitsi-meet.tests.toRun="MaxUsersTest"

I see the first 3 participants joining but then....

[11] Closing web.participant4
[11] TestFailure:
org.openqa.selenium.InvalidArgumentException: invalid argument
  (Session info: chrome=84.0.4147.125)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Spiderman', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-112-generic', java.version: '1.8.0_265'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 84.0.4147.125, chrome: {chromedriverVersion: 84.0.4147.30 (48b3e868b4cc0..., userDataDir: /tmp/.com.google.Chrome.RvjFQk}, goog:chromeOptions: {debuggerAddress: localhost:41297}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 85bc31cbc39ab30687a250854e2d048a
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at org.jitsi.meet.test.web.WebParticipant.doJoinConference(WebParticipant.java:140)
	at org.jitsi.meet.test.base.Participant.joinConference(Participant.java:152)
	at org.jitsi.meet.test.base.Participant.joinConference(Participant.java:122)
	at org.jitsi.meet.test.MaxUsersTest.enterWithMaxParticipantsAndCheckDialog(MaxUsersTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Spiderman', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-112-generic', java.version: '1.8.0_265'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:295)
	at org.jitsi.meet.test.base.Participant.takeScreenshot(Participant.java:472)
	at org.jitsi.meet.test.base.FailureListener.lambda$takeScreenshots$0(FailureListener.java:257)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jitsi.meet.test.base.FailureListener.takeScreenshots(FailureListener.java:256)
	at org.jitsi.meet.test.base.FailureListener.onTestFailure(FailureListener.java:198)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1379)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:624)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[11] End enterWithMaxParticipantsAndCheckDialog.
[11] Closing web.participant1
[11] Closing web.participant2
[11] Closing web.participant4
[ERROR] Tests run: 319, Failures: 1, Errors: 0, Skipped: 318, Time elapsed: 14.453 s <<< FAILURE! - in TestSuite
[ERROR] enterWithMaxParticipantsAndCheckDialog(org.jitsi.meet.test.MaxUsersTest)  Time elapsed: 2.308 s  <<< FAILURE!
org.openqa.selenium.InvalidArgumentException: 
invalid argument
  (Session info: chrome=84.0.4147.125)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Spiderman', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-112-generic', java.version: '1.8.0_265'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 84.0.4147.125, chrome: {chromedriverVersion: 84.0.4147.30 (48b3e868b4cc0..., userDataDir: /tmp/.com.google.Chrome.RvjFQk}, goog:chromeOptions: {debuggerAddress: localhost:41297}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 85bc31cbc39ab30687a250854e2d048a
	at org.jitsi.meet.test.MaxUsersTest.enterWithMaxParticipantsAndCheckDialog(MaxUsersTest.java:92)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MaxUsersTest.enterWithMaxParticipantsAndCheckDialog:92 » InvalidArgument inval...
[INFO] 
[ERROR] Tests run: 319, Failures: 1, Errors: 0, Skipped: 318
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.504 s
[INFO] Finished at: 2020-08-13T18:06:20+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project jitsi-meet-torture: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jsmadeu/jitsi/jitsi-meet-torture/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Please can you tell me what is happening=?

**Comment by ipavlenko** [comment]
I have the same problem.

**Comment by jlemangarin** [comment]
Hello @damencho 

Are you working on this project ? It seems we have a blocker unresolved issue here.

Thank you in advance !

**Comment by jjmasdeu** [comment]
I never solved this issue.. Ive installed the new torture version and now MaxUsersTest is in the default exclude list....

**Comment by felipeavilis** [comment]
Same here. Only 3 participants. When torture try to add the 4th participant, it crashes. More information bellow:

Command executed:
```shell
mvn test -Djitsi-meet.instance.url="https://meet.example.com" -Djitsi-meet.tests.toRun="MaxUsersTest"
```
Output:
```log
[37] Started chrome driver for prefix: web.participant4
[37] web.participant4 is opening URL: https://meet.example.com/jitsimeettorture119412362#config.testing.testMode=true&config.disableNS=true&config.disableAEC=true&config.analytics.disabled=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=true&config.p2p.useStunTurn=false&config.prejoinConfig.enabled=false&config.p2p.enabled=false&config.requireDisplayName=false&config.toolbarConfig.alwaysVisible=true&config.gatherStats=true&config.pcStatsInterval=1500&config.debug=true&config.enableTalkWhileMuted=false&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[37] web.participant4 lib-jitsi-meet version: 5671c5d6 sessionID: 3f20dd5892232162e6fbaa8c41aa36b2
[37] Closing web.participant4
[37] TestFailure:
java.lang.AssertionError: There was no error dialog.
        at org.testng.Assert.fail(Assert.java:110)
        at org.jitsi.meet.test.MaxUsersTest.enterWithMaxParticipantsAndCheckDialog(MaxUsersTest.java:112)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Oct 17, 2024 12:23:26 PM org.jitsi.meet.test.base.FailureListener onTestFailure
SEVERE: Failed to gather debug information for
java.lang.RuntimeException: Failed to move the screenshot file, from: C:\Users\felipe\AppData\Local\Temp\screenshot11877019116699440715.png to: target\surefire-reports\screenshots\org.jitsi.meet.test.MaxUsersTest-web.participant1.png
        at org.jitsi.meet.test.base.Participant.takeScreenshot(Participant.java:481)
        at org.jitsi.meet.test.base.FailureListener.lambda$takeScreenshots$0(FailureListener.java:256)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.jitsi.meet.test.base.FailureListener.takeScreenshots(FailureListener.java:255)
        at org.jitsi.meet.test.base.FailureListener.onTestFailure(FailureListener.java:197)
        at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:99)
        at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:277)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:764)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.apache.commons.io.FileExistsException: File element in parameter 'destFile' already exists: 'target\surefire-reports\screenshots\org.jitsi.meet.test.MaxUsersTest-web.participant1.png'
        at org.apache.commons.io.FileUtils.requireAbsent(FileUtils.java:2693)
        at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2396)
        at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2374)
        at org.jitsi.meet.test.base.Participant.takeScreenshot(Participant.java:475)
        ... 23 more

[37] End enterWithMaxParticipantsAndCheckDialog.
[37] Closing web.participant1
[37] Closing web.participant2
[37] Closing web.participant4
[ERROR] Tests run: 451, Failures: 1, Errors: 0, Skipped: 450, Time elapsed: 25.661 s <<< FAILURE! - in TestSuite
[ERROR] enterWithMaxParticipantsAndCheckDialog(org.jitsi.meet.test.MaxUsersTest)  Time elapsed: 9.025 s  <<< FAILURE!
java.lang.AssertionError: There was no error dialog.
        at org.jitsi.meet.test.MaxUsersTest.enterWithMaxParticipantsAndCheckDialog(MaxUsersTest.java:112)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MaxUsersTest.enterWithMaxParticipantsAndCheckDialog:112 There was no error dialog.
[INFO]
[ERROR] Tests run: 447, Failures: 1, Errors: 0, Skipped: 446
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.957 s
[INFO] Finished at: 2024-10-17T12:23:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jitsi-meet-torture: There are test failures.
[ERROR]
[ERROR] Please refer to C:\tmp\jitsi-meet-torture\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by felipeavilis** [comment]
Ok, i've just tried something... and it worked! 
Edit the file `\jitsi-meet-torture\src\test\java\org\jitsi\meet\test\MaxUsersTest.java` and change the value of `MAX_USERS` from `3` to `10`. Link to file: https://github.com/jitsi/jitsi-meet-torture/blob/0a845b642cf0a5801ae42c55393709980ef26235/src/test/java/org/jitsi/meet/test/MaxUsersTest.java#L43
I couldn’t find any documentation here and, like I said before, I’m not a developer. So, there’s probably a way to change its values via the command line, as a parameter for the Maven run command.

**Comment by damencho** [comment]
And I think we have not ran this test in a while, so maybe its broken. I will take a note and will delete it when I have time.

**Comment by felipeavilis** [comment]
> There is no point of having this configurable ... as this needs to be changed and server side. Because this test depends on server side changes its not supposed to be run by default:
> 
> ```
> public boolean skipTestByDefault()
>     {
>         return true;
>     }
> ```
> 
> This is a manual test, where you modify server to allow max of 3 people, you restart prosody and then run the test.

 I think we’re not on the same page. What I’m talking about is the need to run a heavier test by adding more than 3 simultaneous users during the Jitsi Meet Torture tests. I didn’t know that server-side changes were necessary. And I believe there’s no need for that.

The error we showed was from Jitsi Meet Torture, not from the server.

Also, my comment was that I couldn’t find any other way to change the value from 3 to another number without manually editing the file. That’s all. The tests are running fine

**Comment by damencho** [comment]
> I think we’re not on the same page. What I’m talking about is the need to run a heavier test by adding more than 3 simultaneous users during the Jitsi Meet Torture tests. I didn’t know that server-side changes were necessary. And I believe there’s no need for that.
> 
> The error we showed was from Jitsi Meet Torture, not from the server.
> 
> Also, my comment was that I couldn’t find any other way to change the value from 3 to another number without manually editing the file. That’s all. The tests are running fine

So you seem to misunderstood what does this test do then. This tests this functionality: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_max_occupants.lua
Which has a severside setting: https://github.com/jitsi/jitsi-meet/blob/3d85202987aeaf5de9466db0d79bd464117c3d67/resources/prosody-plugins/mod_muc_max_occupants.lua#L13

**Comment by felipeavilis** [comment]
> > I think we’re not on the same page. What I’m talking about is the need to run a heavier test by adding more than 3 simultaneous users during the Jitsi Meet Torture tests. I didn’t know that server-side changes were necessary. And I believe there’s no need for that.
> > The error we showed was from Jitsi Meet Torture, not from the server.
> > Also, my comment was that I couldn’t find any other way to change the value from 3 to another number without manually editing the file. That’s all. The tests are running fine
> 
> So you seem to misunderstood what does this test do then. This tests this functionality: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_max_occupants.lua Which has a severside setting: https://github.com/jitsi/jitsi-meet/blob/3d85202987aeaf5de9466db0d79bd464117c3d67/resources/prosody-plugins/mod_muc_max_occupants.lua#L13

Ok. Got it. 

But my intention was to use Jitsi Meet Torture to stress test my server, lol.

**Comment by damencho** [comment]
Search the forum for jitsi-meet-load-test, how to enable that and you will need a selenium grid with many machines and you can use then the script: https://github.com/jitsi/jitsi-meet-torture/blob/master/scripts/malleus.sh
It is not a test that will give you true or false. This is a way to stress a system where you can monitor with the tools and monitoring you have already deployed.

**Comment by damencho** [comment]
Use the forum to ask questions and look for help.
