### ISSUE TITLE
[Utils] [ERROR] [Error] java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by clark-97** [jitsi/jitsi-meet-torture#347]
I runed 
```sh
mvn \
-Dthreadcount=1 \
-Dorg.jitsi.malleus.conferences=1 \
-Dorg.jitsi.malleus.participants=20 \
-Dorg.jitsi.malleus.senders=20 \
-Dorg.jitsi.malleus.duration=300 \
-Dorg.jitsi.malleus.room_name_prefix="mytestroom" \
-Dremote.address="http://localhost:4444/wd/hub" \
-Djitsi-meet.tests.toRun=MalleusJitsificus \
-Dremote.resource.path=/usr/share/jitsi-meet-torture \
-Djitsi-meet.instance.url=https://session.example.com \
-Djitsi-meet.isRemote=true \
test
```

but got some java error, following is the all console info:
```sh
clark@LAPTOP-QNA4H49M:/mnt/e/User/Documents/Work/jitsi-meet-torture$ mvn \
> -Dthreadcount=1 \
> -Dorg.jitsi.malleus.conferences=1 \
> -Dorg.jitsi.malleus.participants=20 \
> -Dorg.jitsi.malleus.senders=20 \
> -Dorg.jitsi.malleus.duration=300 \
> -Dorg.jitsi.malleus.room_name_prefix="mytestroom" \
> -Dremote.address="http://localhost:4444/wd/hub" \
> -Djitsi-meet.tests.toRun=MalleusJitsificus \
> -Dremote.resource.path=/usr/share/jitsi-meet-torture \
> -Djitsi-meet.instance.url=https://session.example.com \
> -Djitsi-meet.isRemote=true \
> test
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jitsi-meet-torture 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jitsi-meet-torture ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /mnt/e/User/Documents/Work/jitsi-meet-torture/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ jitsi-meet-torture ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jitsi-meet-torture ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ jitsi-meet-torture ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ jitsi-meet-torture ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[44] testsToRun=[MalleusJitsificus]
[44] testsToExclude=[]
[44] testsToInclude=[]
[44] ---=== Testing MalleusJitsificus ===---
[Utils] [ERROR] [Error] java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:657)
        at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:813)
        at org.jitsi.meet.test.MalleusJitsificus.createData(MalleusJitsificus.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
        at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
        at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
        at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
        at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
        at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
        at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

[WARNING] Tests run: 333, Failures: 0, Errors: 0, Skipped: 333, Time elapsed: 10.548 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 329, Failures: 0, Errors: 0, Skipped: 329
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.284 s
[INFO] Finished at: 2021-02-16T19:36:57+08:00
[INFO] Final Memory: 13M/44M
[INFO] ------------------------------------------------------------------------
clark@LAPTOP-QNA4H49M:/mnt/e/User/Documents/Work/jitsi-meet-torture$
```
I tried to reinstall jitsi-meet-torture, but still get same error

**Comment by JonathanLennox** [comment]
We've added some new parameters to Malleus to support some additional load-testing features.

I suggest using the `scripts/malleus.sh` script to invoke Malleus; that gets updated whenever a new parameter is added.

**Comment by clark-97** [comment]
@JonathanLennox I got another java error
```sh
clark@LAPTOP-QNA4H49M:/mnt/e/User/Documents/Work/jitsi-meet-torture$ scripts/malleus.sh 1 20 20 300 mytestroom http://localhost:4444/wd/hub
Warning: JAVA_HOME environment variable is not set.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building jitsi-meet-torture 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jitsi-meet-torture ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /mnt/e/User/Documents/Work/jitsi-meet-torture/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ jitsi-meet-torture ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jitsi-meet-torture ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ jitsi-meet-torture ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ jitsi-meet-torture ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[45] testsToRun=[MalleusJitsificus]
[45] testsToExclude=[]
[45] testsToInclude=[]
[45] ---=== Testing MalleusJitsificus ===---
[Utils] [ERROR] [Error] java.lang.NumberFormatException: For input string: &quot;&quot;
        at java.lang.NumberFormatException.forInputString(java.base@9-internal/NumberFormatException.java:65)
        at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:705)
        at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:813)
        at org.jitsi.meet.test.MalleusJitsificus.createData(MalleusJitsificus.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
        at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
        at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
        at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
        at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
        at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
        at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
        at java.util.concurrent.FutureTask.run(java.base@9-internal/FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)

[WARNING] Tests run: 333, Failures: 0, Errors: 0, Skipped: 333, Time elapsed: 11.021 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 329, Failures: 0, Errors: 0, Skipped: 329
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.774 s
[INFO] Finished at: 2021-02-17T15:52:10+08:00
[INFO] Final Memory: 13M/44M
[INFO] ------------------------------------------------------------------------
clark@LAPTOP-QNA4H49M:/mnt/e/User/Documents/Work/jitsi-meet-torture$
```

**Comment by JonathanLennox** [comment]
Ah, whoops, that's the backwards-compatible command-line which it looks like I managed to break.  Run with `--help` to see the new usage; I'll update the default behavior to fix the output and the default behavior.

**Comment by JonathanLennox** [comment]
See https://github.com/jitsi/jitsi-meet-torture/pull/348.
