### ISSUE TITLE
jitsi torture not working for video

### ISSUE THREAD

**Issue by bharath-naik** [jitsi/jitsi-meet-torture#502]
Hi
i am Using jitsi-meet-torture. running the below command from jitsi-torture parent directory
```
./scripts/malleus.sh --conferences=1 --participants=5 --senders=1 --audio-senders=2 --duration=120 
--room-name-prefix=hammertesting --hub-url=http://xxx.xxx.xx.1:4444/wd/hub --instance-url=https://xxx.xxx.xx.x:8443/
```
i have a selenium grid setup on the same machine which is both node and hub.

i have kept the the video file at this location
`/usr/share/jitsi-meet-torture/resources/FourPeople_1280x720_30.y4m`
While having a manual video call, it’s working good, there are no issues. But while testing using jitsi-meet-torture the video is not enabled. it appears to be a black screen.

logs 
```
villian@villian:~/Desktop/jitsi-meet-torture-master$ sudo sh scripts/malleus.sh --conferences=1 --participants=5 --senders=1 --audio-senders=2 --duration=200 --room-name-prefix=hamergrows --hub-url=http://192.168.49.1:4444/wd/hub --instance-url=https://socialhour.vewmet.com/
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.jitsi:jitsi-meet-torture >--------------------
[INFO] Building jitsi-meet-torture 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jitsi-meet-torture ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/villian/Desktop/jitsi-meet-torture-master/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ jitsi-meet-torture ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jitsi-meet-torture ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ jitsi-meet-torture ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ jitsi-meet-torture ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
[13] testsToRun=[MalleusJitsificus]
[13] testsToExclude=[]
[13] testsToInclude=[]
[13] ---=== Testing MalleusJitsificus ===---
will run with:
conferences=1
participants=5
senders=1
audio senders=2
duration=200000ms
join delay=0ms
room_name_prefix=hamergrows
enable_p2p=true
max_disrupted_bridges_pct=0.0
regions=null
stage view=false
[14] Start testMain.
[15] No participant type specified for prefix: web.participant1, will use Chrome...
[16] No participant type specified for prefix: web.participant2, will use Chrome...
[18] No participant type specified for prefix: web.participant3, will use Chrome...
[17] No participant type specified for prefix: web.participant4, will use Chrome...
[21] No participant type specified for prefix: web.participant5, will use Chrome...
[pool-1-thread-7] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 99.0.4844.51 (resolved driver for Chrome 99)
[pool-1-thread-4] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 99.0.4844.51 (resolved driver for Chrome 99)
[pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 99.0.4844.51 (resolved driver for Chrome 99)
[pool-1-thread-3] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 99.0.4844.51 (resolved driver for Chrome 99)
[pool-1-thread-2] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 99.0.4844.51 (resolved driver for Chrome 99)
[pool-1-thread-7] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/99.0.4844.51/chromedriver
[pool-1-thread-4] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/99.0.4844.51/chromedriver
[pool-1-thread-3] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/99.0.4844.51/chromedriver
[pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/99.0.4844.51/chromedriver
[pool-1-thread-2] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as /root/.cache/selenium/chromedriver/linux64/99.0.4844.51/chromedriver
Apr 01, 2022 6:05:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 01, 2022 6:05:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 01, 2022 6:05:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 01, 2022 6:05:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 01, 2022 6:05:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[21] Started chrome driver for prefix: web.participant5
[21] web.participant5 is opening URL: https://socialhour.vewmet.com/hamergrows0#config.testing.testMode=true&config.disableNS=true&config.testing.noAutoPlayVideo=true&config.disableAEC=true&config.analytics.disabled=true&config.startWithAudioMuted=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=false&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=true&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=10000&config.debug=true&config.enableTalkWhileMuted=false&config.startWithVideoMuted=true&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[18] Started chrome driver for prefix: web.participant3
[18] web.participant3 is opening URL: https://socialhour.vewmet.com/hamergrows0#config.testing.testMode=true&config.disableNS=true&config.testing.noAutoPlayVideo=true&config.disableAEC=true&config.analytics.disabled=true&config.startWithAudioMuted=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=false&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=true&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=10000&config.debug=true&config.enableTalkWhileMuted=false&config.startWithVideoMuted=true&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[17] Started chrome driver for prefix: web.participant4
[17] web.participant4 is opening URL: https://socialhour.vewmet.com/hamergrows0#config.testing.testMode=true&config.disableNS=true&config.testing.noAutoPlayVideo=true&config.disableAEC=true&config.analytics.disabled=true&config.startWithAudioMuted=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=false&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=true&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=10000&config.debug=true&config.enableTalkWhileMuted=false&config.startWithVideoMuted=true&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[16] Started chrome driver for prefix: web.participant2
[16] web.participant2 is opening URL: https://socialhour.vewmet.com/hamergrows0#config.testing.testMode=true&config.disableNS=true&config.testing.noAutoPlayVideo=true&config.disableAEC=true&config.analytics.disabled=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=false&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=true&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=10000&config.debug=true&config.enableTalkWhileMuted=false&config.startWithVideoMuted=true&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[15] Started chrome driver for prefix: web.participant1
[15] web.participant1 is opening URL: https://socialhour.vewmet.com/hamergrows0#config.testing.testMode=true&config.disableNS=true&config.testing.noAutoPlayVideo=true&config.disableAEC=true&config.analytics.disabled=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=false&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=true&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=10000&config.debug=true&config.enableTalkWhileMuted=false&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[21] web.participant5 lib-jitsi-meet version: 97ff597425 sessionID: 09e5e6081d40390ed9be4a27d6966eae
[15] web.participant1 lib-jitsi-meet version: 97ff597425 sessionID: d97afabc814cf17ae9d2d90b8f7f533e
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 28.815
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.4IXagD}, goog:chromeOptions: {debuggerAddress: localhost:38675}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 67b82702a9d810a94297e3230aa...}
Session ID: 67b82702a9d810a94297e3230aa05061
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at org.jitsi.meet.test.web.WebParticipant.doJoinConference(WebParticipant.java:190)
	at org.jitsi.meet.test.base.Participant.joinConference(Participant.java:158)
	at org.jitsi.meet.test.MalleusJitsificus$MalleusTask.join(MalleusJitsificus.java:379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 28.812
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.uSdG9X}, goog:chromeOptions: {debuggerAddress: localhost:44155}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 33fdfc5d56d054040ebc7fa8d46...}
Session ID: 33fdfc5d56d054040ebc7fa8d4650346[18] TimeoutException while loading page, will skip it and continue:timeout: Timed out receiving message from renderer: 28.815
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.4IXagD}, goog:chromeOptions: {debuggerAddress: localhost:38675}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 67b82702a9d810a94297e3230aa...}
Session ID: 67b82702a9d810a94297e3230aa05061

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at org.jitsi.meet.test.web.WebParticipant.doJoinConference(WebParticipant.java:190)
	at org.jitsi.meet.test.base.Participant.joinConference(Participant.java:158)
	at org.jitsi.meet.test.MalleusJitsificus$MalleusTask.join(MalleusJitsificus.java:379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[17] TimeoutException while loading page, will skip it and continue:timeout: Timed out receiving message from renderer: 28.812
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.uSdG9X}, goog:chromeOptions: {debuggerAddress: localhost:44155}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 33fdfc5d56d054040ebc7fa8d46...}
Session ID: 33fdfc5d56d054040ebc7fa8d4650346
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 28.816
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.l3UI4R}, goog:chromeOptions: {debuggerAddress: localhost:34395}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 49c7facee4ceedeedf1e3154729...}
Session ID: 49c7facee4ceedeedf1e31547298296e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at org.jitsi.meet.test.web.WebParticipant.doJoinConference(WebParticipant.java:190)
	at org.jitsi.meet.test.base.Participant.joinConference(Participant.java:158)
	at org.jitsi.meet.test.MalleusJitsificus$MalleusTask.join(MalleusJitsificus.java:379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[16] TimeoutException while loading page, will skip it and continue:timeout: Timed out receiving message from renderer: 28.816
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.l3UI4R}, goog:chromeOptions: {debuggerAddress: localhost:34395}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 49c7facee4ceedeedf1e3154729...}
Session ID: 49c7facee4ceedeedf1e31547298296e
[18] web.participant3 lib-jitsi-meet version: 97ff597425 sessionID: 67b82702a9d810a94297e3230aa05061
[17] web.participant4 lib-jitsi-meet version: 97ff597425 sessionID: 33fdfc5d56d054040ebc7fa8d4650346
[20] Hung up in web.participant3.
[15] Hung up in web.participant4.
[16] Hung up in web.participant5.
[19] Hung up in web.participant1.
[19] Closing web.participant1
[15] Closing web.participant4
[20] Closing web.participant3
[16] Closing web.participant5
[14] TestFailure:
java.lang.Exception: Failed with multiple errors. Throws the primary.
	at org.jitsi.meet.test.MalleusJitsificus.testMain(MalleusJitsificus.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.JavascriptException: javascript error: APP is not defined
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.l3UI4R}, goog:chromeOptions: {debuggerAddress: localhost:34395}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 49c7facee4ceedeedf1e3154729...}
Session ID: 49c7facee4ceedeedf1e31547298296e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at org.jitsi.meet.test.web.WebParticipant.executeScript(WebParticipant.java:287)
	at org.jitsi.meet.test.web.WebParticipant.doJoinConference(WebParticipant.java:215)
	at org.jitsi.meet.test.base.Participant.joinConference(Participant.java:158)
	at org.jitsi.meet.test.MalleusJitsificus$MalleusTask.join(MalleusJitsificus.java:379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
Apr 01, 2022 6:08:50 PM org.jitsi.meet.test.base.FailureListener onTestFailure
SEVERE: Failed to gather debug information for 
java.lang.NullPointerException
	at org.jitsi.meet.test.base.FailureListener.lambda$takeScreenshots$0(FailureListener.java:258)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.jitsi.meet.test.base.FailureListener.takeScreenshots(FailureListener.java:255)
	at org.jitsi.meet.test.base.FailureListener.onTestFailure(FailureListener.java:197)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1379)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:624)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[14] End testMain.
[13] Closing web.participant2
[ERROR] Tests run: 445, Failures: 1, Errors: 0, Skipped: 444, Time elapsed: 202.504 s <<< FAILURE! - in TestSuite
[ERROR] testMain(org.jitsi.meet.test.MalleusJitsificus)  Time elapsed: 201.451 s  <<< FAILURE!
java.lang.Exception: Failed with multiple errors. Throws the primary.
	at org.jitsi.meet.test.MalleusJitsificus.testMain(MalleusJitsificus.java:280)
Caused by: org.openqa.selenium.JavascriptException: 
javascript error: APP is not defined
  (Session info: chrome=99.0.4844.84)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'villian', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.13.0-37-generic', java.version: '1.8.0_312'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 99.0.4844.84, chrome: {chromedriverVersion: 99.0.4844.51 (d537ec02474b5..., userDataDir: /tmp/.com.google.Chrome.l3UI4R}, goog:chromeOptions: {debuggerAddress: localhost:34395}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 49c7facee4ceedeedf1e3154729...}
Session ID: 49c7facee4ceedeedf1e31547298296e

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MalleusJitsificus.testMain:280  Failed with multiple errors. Throws the primar...
[INFO] 
[ERROR] Tests run: 441, Failures: 1, Errors: 0, Skipped: 440
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:23 min
[INFO] Finished at: 2022-04-01T18:08:51+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jitsi-meet-torture: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/villian/Desktop/jitsi-meet-torture-master/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by damencho** [comment]
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 28.815

Indicates your chrome is struggling to work normally on that machine

**Comment by damencho** [comment]
You need 4GB for a chrome instance.

**Comment by bharath-naik** [comment]
thanks @damencho . it worked
