### ISSUE TITLE
Problem with Peer2PeerTest

### ISSUE THREAD

**Issue by DiederikE** [jitsi/jitsi-meet-torture#628]
Hello I don't know where to submit this on the community, but I have a problem with running the Peer2PeerTest.

These are the logs:

[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.jitsi:jitsi-meet-torture >--------------------
[INFO] Building jitsi-meet-torture 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- resources:3.3.0:resources (default-resources) @ jitsi-meet-torture ---
[INFO] skip non existing resourceDirectory /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ jitsi-meet-torture ---
[INFO] No sources to compile
[INFO] 
[INFO] --- resources:3.3.0:testResources (default-testResources) @ jitsi-meet-torture ---
[INFO] Copying 0 resource
[INFO] Copying 2 resources
[INFO] The encoding used to copy filtered properties files have not been set. This means that the same encoding will be used to copy filtered properties files as when copying other filtered resources. This might not be what you want! Run your build with --debug to see which files might be affected. Read more at https://maven.apache.org/plugins/maven-resources-plugin/examples/filtering-properties-files.html
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ jitsi-meet-torture ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 129 source files with javac [debug release 11] to target/test-classes
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/base/AbstractBaseTest.java:[129,15] deprecated item is not annotated with @Deprecated
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/base/TypedBaseTest.java:[56,15] deprecated item is not annotated with @Deprecated
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/web/WebTestBase.java:[46,12] deprecated item is not annotated with @Deprecated
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/StopVideoTest.java:[47,12] deprecated item is not annotated with @Deprecated
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/MuteTest.java:[48,12] deprecated item is not annotated with @Deprecated
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/DisplayNameTest.java:[64,12] deprecated item is not annotated with @Deprecated
[WARNING] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/SwitchVideoTest.java:[47,12] deprecated item is not annotated with @Deprecated
[INFO] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/base/FailureListener.java: Some input files use or override a deprecated API.
[INFO] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/base/FailureListener.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/base/FailureListener.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/src/test/java/org/jitsi/meet/test/base/FailureListener.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- surefire:2.22.2:test (default-test) @ jitsi-meet-torture ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/diederikey/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[38] testsToRun=[Peer2PeerTest]
[38] testsToExclude=[]
[38] testsToInclude=[]
[38] ---=== Testing Peer2PeerTest ===---
[38] Start testSwitchToP2P.
[38] No participant type specified for prefix: web.participant1, will use Chrome...
Dec 06, 2023 3:22:58 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 119, so returning the closest version found: 117
[39] ChromeDriver created for:1022 ms.
[38] Started chrome driver for prefix: web.participant1
[38] web.participant1 is opening URL: https://meet.jit.si/jitsimeettorture569270274#config.testing.testMode=true&config.disableNS=true&userInfo.displayName="participant1"&config.disableAEC=true&config.analytics.disabled=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=true&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=false&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=1500&config.debug=true&config.enableTalkWhileMuted=false&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[38] web.participant1 lib-jitsi-meet version: 85f533cf sessionID: 0136600b30b38b6dff68f2481275cf6f
Dec 06, 2023 3:23:09 PM org.jitsi.meet.test.web.WebTestBase joinParticipantAndWait
WARNING: Participant did not join, retrying: web.participant1
[38] Closing web.participant1
[38] No participant type specified for prefix: web.participant1, will use Chrome...
Dec 06, 2023 3:23:11 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 119, so returning the closest version found: 117
[59] ChromeDriver created for:628 ms.
[38] Started chrome driver for prefix: web.participant1
[38] web.participant1 is opening URL: https://meet.jit.si/jitsimeettorture569270274#config.testing.testMode=true&config.disableNS=true&userInfo.displayName="participant1"&config.disableAEC=true&config.analytics.disabled=true&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&config.disable1On1Mode=true&config.alwaysVisibleToolbar=true&config.p2p.useStunTurn=false&config.prejoinConfig.enabled=false&config.p2p.enabled=true&config.requireDisplayName=false&config.gatherStats=true&config.pcStatsInterval=1500&config.debug=true&config.enableTalkWhileMuted=false&config.callStatsID=false&interfaceConfig.DISABLE_FOCUS_INDICATOR=true
[38] web.participant1 lib-jitsi-meet version: 85f533cf sessionID: 9b925999f08adaa5a667114c1156dab4
[38] TestFailure:
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for WebParticipant[web.participant1]@765274207#waitToJoinMUC (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.1', java.version: '19.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.199, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: /var/folders/hy/q6jnds693qb...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51386}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:51386/devtoo..., se:cdpVersion: 119.0.6045.199, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9b925999f08adaa5a667114c1156dab4
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:230)
	at org.jitsi.meet.test.util.TestUtils.waitForCondition(TestUtils.java:546)
	at org.jitsi.meet.test.util.TestUtils.waitForCondition(TestUtils.java:560)
	at org.jitsi.meet.test.base.Participant.waitForCondition(Participant.java:384)
	at org.jitsi.meet.test.base.Participant.waitToJoinMUC(Participant.java:330)
	at org.jitsi.meet.test.base.Participant.waitToJoinMUC(Participant.java:321)
	at org.jitsi.meet.test.web.WebTestBase.joinParticipantAndWait(WebTestBase.java:447)
	at org.jitsi.meet.test.web.WebTestBase.ensureOneParticipant(WebTestBase.java:82)
	at org.jitsi.meet.test.web.WebTestBase.ensureTwoParticipantsInternal(WebTestBase.java:151)
	at org.jitsi.meet.test.web.WebTestBase.ensureTwoParticipants(WebTestBase.java:126)
	at org.jitsi.meet.test.web.WebTestBase.ensureTwoParticipants(WebTestBase.java:104)
	at org.jitsi.meet.test.Peer2PeerTest.testSwitchToP2P(Peer2PeerTest.java:49)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Dec 06, 2023 3:23:22 PM org.jitsi.meet.test.base.FailureListener onTestFailure
SEVERE: Failed to gather debug information for 
java.lang.RuntimeException: Failed to move the screenshot file, from: /var/folders/hy/q6jnds693qbb_gchf9mhjll00000gn/T/screenshot14286900071710663542.png to: target/surefire-reports/screenshots/org.jitsi.meet.test.Peer2PeerTest-web.participant1.png
	at org.jitsi.meet.test.base.Participant.takeScreenshot(Participant.java:481)
	at org.jitsi.meet.test.base.FailureListener.lambda$takeScreenshots$0(FailureListener.java:256)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.jitsi.meet.test.base.FailureListener.takeScreenshots(FailureListener.java:255)
	at org.jitsi.meet.test.base.FailureListener.onTestFailure(FailureListener.java:197)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:99)
	at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:277)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:764)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.apache.commons.io.FileExistsException: File element in parameter 'destFile' already exists: 'target/surefire-reports/screenshots/org.jitsi.meet.test.Peer2PeerTest-web.participant1.png'
	at org.apache.commons.io.FileUtils.requireAbsent(FileUtils.java:2693)
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2396)
	at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2374)
	at org.jitsi.meet.test.base.Participant.takeScreenshot(Participant.java:475)
	... 23 more

[38] End testSwitchToP2P.
[38] Closing web.participant1
[ERROR] Tests run: 453, Failures: 1, Errors: 0, Skipped: 452, Time elapsed: 26.868 s <<< FAILURE! - in TestSuite
[ERROR] testSwitchToP2P(org.jitsi.meet.test.Peer2PeerTest)  Time elapsed: 25.216 s  <<< FAILURE!
org.openqa.selenium.TimeoutException: 
Expected condition failed: waiting for WebParticipant[web.participant1]@765274207#waitToJoinMUC (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.1.1', java.version: '19.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.199, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: /var/folders/hy/q6jnds693qb...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51386}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: mac, proxy: Proxy(), se:cdp: ws://localhost:51386/devtoo..., se:cdpVersion: 119.0.6045.199, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 9b925999f08adaa5a667114c1156dab4
	at org.jitsi.meet.test.Peer2PeerTest.testSwitchToP2P(Peer2PeerTest.java:49)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   Peer2PeerTest.testSwitchToP2P:49->WebTestBase.ensureTwoParticipants:104->WebTestBase.ensureTwoParticipants:126->WebTestBase.ensureTwoParticipantsInternal:151->WebTestBase.ensureOneParticipant:82->WebTestBase.joinParticipantAndWait:447 » Timeout
[INFO] 
[ERROR] Tests run: 449, Failures: 1, Errors: 0, Skipped: 448
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.903 s
[INFO] Finished at: 2023-12-06T15:23:23+01:00
[INFO] ------------------------------------------------------------------------
[WARNING] 
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-surefire-plugin:2.22.2
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jitsi-meet-torture: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/diederikey/Documents/School/PrivacyProj/test/jitsi-meet-torture/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by damencho** [comment]
What are the machine specs that run chrome, RAM and CPU?

**Comment by DiederikE** [comment]
Hello, thanks for the response.

CPU: Apple M1 Pro
RAM: 16 GB
